### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by bassrock** [RNCryptor/RNCryptor-php#12]
I keep getting the following notices in my Apache Log:

Not sure if this is a big deal but just logging it here for reference:

```console
[Thu Apr 14 11:08:00.184364 2016] [:error] [pid 3333] [client 10.0.3.85:17627] PHP Notice:  Uninitialized string offset: 0 in vendor/rncryptor/rncryptor/lib/RNCryptor/Decryptor.php on line 63
[Thu Apr 14 11:08:00.184430 2016] [:error] [pid 3333] [client 10.0.3.85:17627] PHP Notice:  Uninitialized string offset: 1 in vendor/rncryptor/rncryptor/lib/RNCryptor/Decryptor.php on line 68
```

**Comment by curtisdf** [comment]
Are you sure you are passing a base64-encoded encrypted value into the decrypt() function?  The error you are getting would happen if an empty value (false, null, or empty string) was being passed into it.
