### ISSUE TITLE
Unsupported schema version 5 when decrypt encrypted string

### ISSUE THREAD

**Issue by karmamaster** [RNCryptor/RNCryptor-php#14]
Hello,
I have an encrypted string like this:
`BQPafXL85Mc01lu9cyWthMxlwdi7uYXdE/jlbNo7LAJZBdKBhw9gdejwgSEJAJFUjjykSdYMmMnE9gUZdlpiHh6u6MJ/mXy3tRjOdwTfsq87dxCck+QCob6ZRPlC0Ysv3uvCSDIeNv8/imR7KOXbxTYh8cZzHm36ZBR4ivH91+iiLBdnmH7flP/zHBY/12CoTZ2A`

But when i put to decrypt function the code warning to me this error:
` Exception: Unsupported schema version 5 in D:\Hosting_Local\wamp\www\test\lib\RNCryptor\Cryptor.php on line 70`
When i check line 70 on Cryptor.php i saw that the code just have 0 -> 3 version of encryption. So why do the hash return version 5? further more i notice that the encrypted hash will have some format like this:
`AW + [the rest of encrypted hash]`
But in the hash client sent to me i see the format has changed to:
`BQ + [the rest of encrypted hash]`
Do i have some way to know which version or config that the client used to encrypt this? it's kinda weird to normal hash of RNCryptor which i am using so i don't know how to decrypt this hash to orginal source.

**Comment by rnapier** [comment]
Your encrypted string is not in RNCryptor format. I don't know what you mean by "the hash" here. The RNCryptor format is an encryption format, not a hashing format. I don't know what "AW" and "BQ" are here or how they relate to RNCryptor.

I suspect that you're trying to decrypt something that was not encrypted by RNCryptor at all. See the [FAQ](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format) on this.

**Comment by karmamaster** [comment]
I am sorry, i mean encrypted string not "hash".  I believe that the string:
`BQPafXL85Mc01lu9cyWthMxlwdi7uYXdE/jlbNo7LAJZBdKBhw9gdejwgSEJAJFUjjykSdYMmMnE9gUZdlpiHh6u6MJ/mXy3tRjOdwTfsq87dxCck+QCob6ZRPlC0Ysv3uvCSDIeNv8/imR7KOXbxTYh8cZzHm36ZBR4ivH91+iiLBdnmH7flP/zHBY/12CoTZ2A`
Came from RNCryptor but maybe in another config?

**Comment by rnapier** [comment]
Why do you believe this ciphertext came from RNCryptor? You'll have to consult the code that generated it. The first two bytes are 0x0503. 0x03 is a proper RNCryptor start byte. 0x05 is not. This is not configurable. (Of course people are free to modify the format any way they want in their own code, but it won't be the RNCryptor format anymore.) Again, go look at the encrypting code and see what it's doing.

**Comment by karmamaster** [comment]
In my case the client is not (don't want) send to me the encrypting code so i must guest and try to many encrypt methods (although they told me they use RNCryptor). Do you have any solution to identify which encrypt is this?

**Comment by karmamaster** [comment]
Can you point me out how to remove the first two bytes?. As you said 0x0503 to 0x03?

**Comment by rnapier** [comment]
I'm not a PHP developer. If you look at the code, though, it includes examples of decoding and modifying the data. You're going to have to convert it to bytes first (`base64_decode`) and then modify the resulting array. You may have to re-encode the data before passing it to the decryptor. Working with raw bytes this way is a prerequisite for any kind of non-trivial crypto work. If you're struggling here, you'll need to study how PHP works with raw data, and how Base64 encoding converts to and from raw data, before proceeding. I don't understand how you have a client who has encoded some data but won't tell you how they encoded it. You likely will need to work that out with your client or this is going to be a very complicated reverse-engineering problem that we won't be able to assist much with.

**Comment by JavaMachine** [comment]
Please provide details, How you got you "Encrypted String" ?

**Comment by karmamaster** [comment]
@JavaMachine i got it from a tweak from user's jailbroken iphone. I have tried to reverse the code from tweak but i only findout that they are using RnCryptor with somekind of CCCryptor. You can take a peek at if you want! just tell me i will upload it, they don't provide me how they encrypt their string

**Comment by rnapier** [comment]
I don't believe we can assist with this reverse engineering effort.
