### ISSUE TITLE
Cryptor.php with PHP 5.3.13

### ISSUE THREAD

**Issue by marinoCr** [RNCryptor/RNCryptor-php#16]
Hi

The server where I try RNCryptor (latest version of both iOS and php) work with PHP 5.3.13. The function hash_pbkdf2 called in cryptor.php doesn't exist so I replaced the line 

		return hash_pbkdf2($this->_settings->pbkdf2->prf, $password, $salt, $this->_settings->pbkdf2->iterations, $this->_settings->pbkdf2->keyLength, true);

with a class found in php.net.
Then I changed the function _generateKey as follow

public function _generateKey($salt, $password) {

		if ($this->_settings->truncatesMultibytePasswords) {
			$utf8Length = mb_strlen($password, 'utf-8');
			$password = substr($password, 0, $utf8Length);
		}

		$hash =  $this->hash_pbkdf2($this->_settings->pbkdf2->prf, $password, $salt, $this->_settings->pbkdf2->iterations, $this->_settings->pbkdf2->keyLength, true);
        return $hash;
	}

introducing the function

public function hash_pbkdf2($algorithm, $password, $salt, $count, $key_length, $raw_output = false) 
	{
        		$data = array('algorithm' => $algorithm, 'password' => $password, 'salt' => $salt, 'count' => $count, 'key_length' => $key_length, 'raw_output' => $raw_output);
        		try {
            		$pbkdf2 = new pbkdf2($data);
            		return $pbkdf2->hash();
        		} catch (Exception $e) {
            		throw $e;
        		}
    }

and the class

        class pbkdf2  extends Cryptor {
            public $algorithm;
            public $password;
            public $salt;
            public $count;
            public $key_length;
            public $raw_output;

            private $hash_length;
            private $output         = "";

            public function __construct($data = null)
            {
                if ($data != null) {
                    $this->init($data);
                }
            }

            public function init($data)
            {
                $this->algorithm  = $data["algorithm"];
                $this->password   = $data["password"];
                $this->salt       = $data["salt"];
                $this->count      = $data["count"];
                $this->key_length = $data["key_length"];
                $this->raw_output = $data["raw_output"];
            }

            public function hash()
            {
                $this->algorithm = strtolower($this->algorithm);
                if(!in_array($this->algorithm, hash_algos(), true))
                    throw new Exception('PBKDF2 ERROR: Invalid hash algorithm.');

                if($this->count <= 0 || $this->key_length <= 0)
                    throw new Exception('PBKDF2 ERROR: Invalid parameters.');

                $this->hash_length = strlen(hash($this->algorithm, "", true));
                $block_count = ceil($this->key_length / $this->hash_length);
                for ($i = 1; $i <= $block_count; $i++) {
                    // $i encoded as 4 bytes, big endian.
                    $last = $this->salt . pack("N", $i);
                    // first iteration
                    $last = $xorsum = hash_hmac($this->algorithm, $last, $this->password, true);
                    // perform the other $this->count - 1 iterations
                    for ($j = 1; $j < $this->count; $j++) {
                        $xorsum ^= ($last = hash_hmac($this->algorithm, $last, $this->password, true));
                    }
                    $this->output .= $xorsum;
                    if($this->raw_output)
                        return substr($this->output, 0, $this->key_length);
                    else
                        return bin2hex(substr($this->output, 0, $this->key_length));
                }
            }

		}
	
found in php.net.

I have a problem decrypting  a string generated by a simple iOS app, transmitted to a simple php module on the server that only GET the crypted string and try to decrypting it (null string returned), the question is:

may these changes in cryptor.php module could compromise the decrypting process?

Thanks in advance
Marino

**Comment by JavaMachine** [comment]
You should use [https://github.com/sarciszewski/php-future](https://github.com/sarciszewski/php-future) which should supply lack of `hash_pbkdf2()`

**Comment by JavaMachine** [comment]
+Also make sure that iOS app generated 'Encrypted String' must be in 'base64' when 'Decrypting' with PHP Library

**Comment by marinoCr** [comment]
Thanks for your suggest. But with the second part of the answer you opened another chapter.

I use this statements to encrypt

    NSString *text = @"Testo da Cifrare";
    NSString *secretKey = @"1234567890123456";
    NSData *data = [text dataUsingEncoding:NSUTF8StringEncoding];
    NSData *NSDataCifrata = [RNEncryptor encryptData:data
                                        withSettings:kRNCryptorAES256Settings
                                            password:secretKey
                                               error:&error];
    NSString *encryptedString = [NSDataCifrata base64EncodedStringWithOptions:0];
    encryptedString = [encryptedString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    NSString *stringaCifrata = [[NSString alloc] initWithData:[NSDataCifrata base64EncodedDataWithOptions:0] encoding:[NSString defaultCStringEncoding]];

and then I send stringaCifrata. But IOS encrypted string is :

AwEmqlREcHOY2OVzBl+WpHWfsq9HKaqw6kHcWBJE/CGZNWqJWy3EzFhD6y5sxAshe+e9W6QRpYUiubXiAZC2q5ZZxs9eSgS0JMdl9XTINKSKsaO9IXzb8M22BeFHjZCGzIA=

when I pass it to php, and is GET in php

AwEmqlREcHOY2OVzBl WpHWfsq9HKaqw6kHcWBJE/CGZNWqJWy3EzFhD6y5sxAshe e9W6QRpYUiubXiAZC2q5ZZxs9eSgS0JMdl9XTINKSKsaO9IXzb8M22BeFHjZCGzIA=

where "+" sign become a space. Result: not decrypted...

So, what is the right encoding sequence?

Thanks a lot

**Comment by curtisdf** [comment]
The lack of `hash_pbkdf2` means you have not installed the dependencies for RNCryptor-php.  Learn [Composer](http://getcomposer.org) and use it.  It will save you a million headaches with dependency management.  Almost every modern PHP library these days is built with the assumption that you are using Composer with your project.

Secondly, the "+" being turned into a space indicates that you have issues with HTTP encoding either on the sending or receiving side.  You might need to pass the string through `rawurlencode()` on the sending side (or equivalent for whatever language you are using), and then use `rawurldecode()` on the receiving side before you try to decrypt.
