### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by bassrock** [RNCryptor/RNCryptor-php#17]
In php 7.1 mcrypt is deprecated for OpenSSL

```
Deprecated: Function mcrypt_create_iv() is deprecated
```

Is there plans to switch it to openssl?

**Comment by bassrock** [comment]
Looks like someone has a fork with it. Anyway to get this into the main library?

https://github.com/beatuslapis/RNCryptor-php/commit/c4dc2cd0226f6481ee138f0a6afef3941b83af1f

**Comment by curtisdf** [comment]
Thanks @bassrock.  This is the first I'd heard of `mcrypt` being deprecated.  We'll take a look at merging the code from that fork.

Note to self: Here is confirmation of `mcrypt`'s deprecation: http://php.net/manual/en/migration71.deprecated.php

**Comment by bassrock** [comment]
@curtisdf  Same when I started the upgrade to 7.1 a few hours ago.

**Comment by curtisdf** [comment]
@bassrock I've played around with @beatuslapis's changes, but one important unit test (actually 4 of them in one) fail when run in php7.1 with `mcrypt` uninstalled.  I'm getting the exact same errors both with my port as well as their fork.  So I don't yet have confidence that their changes truly work in that environment.

I am planning to dig into it more this week.  Several other things about PHP-RNCryptor need modernization too, so I guess this is a good time to bundle them all together.  The best workarounds I can think of for now are to avoid running it in 7.1 if possible, or run with 7.1 but install mcrypt and configure your php.ini error handling settings to squelch that error about mcrypt being deprecated.

**Comment by curtisdf** [comment]
@bassrock I have just released a major refactoring and overhaul of this codebase, which incorporates @beatuslapis's changes.  Tests pass now.  It supports only PHP 7.0 and beyond.  Please let me know if this works for you.  Thanks!

**Comment by bassrock** [comment]
Oh wow. That was awesomely fast!!!! I will try it out now thanks so much @curtisdf!

**Comment by beatuslapis** [comment]
Actually, I also felt that it might be needed some refactorings and didn't have enough confidences on my changes that time.
However, those changes were enough for my situations.
Reasons why I had not suggested a PR for this. 😋 

Anyway, I'm also very glad to get new, neat updates.
Thanks so much @curtisdf for updates.
Also grateful to @bassrock for mentioning. 😅

**Comment by mvik86** [comment]
Thanks a lot @curtisdf for this updates, 
If this was not fixed we need to replace this with something else. But we are relaxed now.

also I want to say thanks to @bassrock to mentioning this issue.

**Comment by bassrock** [comment]
Forgot to respond!! Been using it since the changes it works great! Thanks @curtisdf
