### ISSUE TITLE
Class 'RNCryptor\RNCryptor\Encryptor' not found 

### ISSUE THREAD

**Issue by BaherHosni** [RNCryptor/RNCryptor-php#19]
Hello

Thank you so much for the great effort. I seem to have a problem with accessing the functionality of this library. I am new to Composer and I seem to have a problem with understanding wich "autoloader.php" to require in the code. I am simply using the supplied "encrypt.php" example and getting the "Class 'RNCryptor\RNCryptor\Encryptor' not found " no matter which autoloader I try to require. 

I am working on a shared hosting server where my composer got installed in .php and "vendor" got installed in the application user directory "~/" next to ".php". 

I am thinking my problem is not requiring the correct autoloader.php and/or instantiating the correct classpath 'RNCryptor\RNCryptor\Encryptor'. 

I hope you can help me with this pit hole

Baher

**Comment by BaherHosni** [comment]
1/2 an hour later...
Nevermind.. My bad.. all working fine! :-)

**Comment by F3L1X79** [comment]
For those you want to save half an hour, I had exactly the same problem and corrected it by changing slightly the path from the examples:
`$cryptor = new \RNCryptor\Encryptor; //instead of $cryptor = new \RNCryptor\Encryptor;`
