### ISSUE TITLE
is it normal?

### ISSUE THREAD

**Issue by spring-pro** [RNCryptor/RNCryptor-php#20]
'??' - is it normal in 98 & 99 row in Ecrypt.php file?

**Comment by Anxiro** [comment]
Long time ago he posted this and I shouldn't reply. But for those who want to know:

The double '??' is called a _[Null coalescing operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)_, which is introduced in PHP7.

**Comment by curtisdf** [comment]
@Anxiro is correct. It's a php7 thing.
