### ISSUE TITLE
Encrypt with objc decrypt PHP problem

### ISSUE THREAD

**Issue by imrepapp** [RNCryptor/RNCryptor-php#21]
Hi,
ObjC side encryption: (Using RNCryptor (3.0.1))

    NSData *data = [@"TEST STRING" dataUsingEncoding:NSUTF8StringEncoding];
    NSError *error;
    NSData *encryptedData = [RNEncryptor encryptData:data
                                        withSettings:kRNCryptorAES256Settings
                                            password:@"myPassword"
                                               error:&error];
    if (error == nil) {
        NSString* output = [encryptedData base64EncodedStringWithOptions:0];
    }

PHP side decryption: (rncryptor/rncryptor 3.1.4 on Windows + PHP5.4.45 + mcrypt 2.5.8)
   
    $decryptor = new \RNCryptor\Decryptor;
    $password = "myPassword";
    $base64Encrypted = "AwEpke5sjJK7vtz3Nt4BuJg8/BU03AiguUkl7BlYXOyY8A1MqyOwH5BRub+XBiPZDVWeYZ512XVU/wkL/J+d72NzQeSc4NFri5aAk0hCGbgpbA==";
    echo "Base64 Encrypted:\n$base64Encrypted\n\n";
    $decrypted = $decryptor->decrypt($base64Encrypted, $password);
    echo "Plaintext:\n$decrypted\n\n";

If I do the encrypt/decrypt on the same side or I do the decryption in PHP CLI (5.6) on my mac it works fine. Do you know any issue what could cause this? 

Regards,
Imre

**Comment by maledettobue** [comment]
I copied your resulting string and your password, then tested it on my end (PHP side) and it works. When I saw your string, I thought the problem was the plus sign but, since the string is hardcoded, this should not be the case for rawurlencode, etc.

**Comment by curtisdf** [comment]
We get a lot of error reports from folks not urlencoding the encrypted string before passing it through HTTP.  Sounds like that's the issue here.  Feel free to reopen or submit a new issue if not.
