### ISSUE TITLE
Function mcrypt_create_iv() is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by sicaboy** [RNCryptor/RNCryptor-php#22]
Function mcrypt_create_iv() is deprecated in PHP 7.1
File:
/lib/RNCryptor/Encryptor.php 
Line: 
114

Function mcrypt_encrypt() is deprecated in PHP 7.1
File:
/lib/RNCryptor/Encryptor.php 
Line: 
82

**Comment by curtisdf** [comment]
Latest version factors this out in favor of using openssl functions.  Please upgrade and you should be all set.

**Comment by F3L1X79** [comment]
When I use composer` composer require rncryptor/rncryptor` it looks like it didn't get the latest version (still get mcrypt) in Cryptor.php. Any clue why?

**Comment by sicaboy** [comment]
You outta force the branch in composer.json

**Comment by curtisdf** [comment]
@F3L1X79 the master branch has the openssl version.  There is no special tagging or branching needed.  If you didn't get the openssl version, then it makes me suspect that something else in your project's `composer.json` or your software stack prevented it.  Are you running PHP 7.0 or 7.1?  Do you have the `openssl` extension installed?

**Comment by F3L1X79** [comment]
@curtisdf thanks a bunch. My current version of PHP is 5.6.11. Guess that's why. Sorry for disturbing and thank you again for the good package!
