### ISSUE TITLE
Receiving an error message 

### ISSUE THREAD

**Issue by jaay20** [RNCryptor/RNCryptor-php#26]
Respected vendor please look into the following error message;

PHP Parse error:  syntax error, unexpected '?' in .../rncryptor/src/RNCryptor/Encryptor.php on line 99

regards

**Comment by curtisdf** [comment]
Your PHP version does not appear to support the Null Coalescing Operator `??`, which was introduced in PHP 7.0.  What version are you using? This library is written only for PHP 7 and up.
