### ISSUE TITLE
How do I convert C# Rijndael encryption to PHP 

### ISSUE THREAD

**Issue by baaslaawe** [RNCryptor/RNCryptor-php#27]
I'm trying to encrypt and decrypt data between client (C#) and server PHP.

i don't understand encryption enough to work out

so i need to convert C# to php thanks

Any help is appreciated.

here is my code: C#:
       

 private static readonly string PasswordHash = "P@@Sw0rd";
        private static readonly string SaltKey = "S@LT&KEY";
        private static readonly string VIKey = "@1B2c3D4e5F6g7H8";
    
        static void Main(string[] args)
        {
      
            string message = "test@123";

         
            string encrypted = Encrypt(message);

            string DecryptString = encrypted;
            string decrypted = Decrypt(DecryptString);
            Console.WriteLine(encrypted);

  
        }
        
 
        public static string Encrypt(string plainText)
        {
            byte[] bytes1 = Encoding.UTF8.GetBytes(plainText);
            byte[] bytes2 = new Rfc2898DeriveBytes(PasswordHash, Encoding.ASCII.GetBytes(SaltKey)).GetBytes(32);

            RijndaelManaged rijndaelManaged = new RijndaelManaged();
            rijndaelManaged.Mode = CipherMode.CBC;
            rijndaelManaged.Padding = PaddingMode.Zeros;
            ICryptoTransform encryptor = rijndaelManaged.CreateEncryptor(bytes2, Encoding.ASCII.GetBytes(VIKey));
            byte[] array;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                using (CryptoStream cryptoStream = new CryptoStream((Stream)memoryStream, encryptor, CryptoStreamMode.Write))
                {
                    cryptoStream.Write(bytes1, 0, bytes1.Length);
                    cryptoStream.FlushFinalBlock();
                    array = memoryStream.ToArray();
                    cryptoStream.Close();
                }
                memoryStream.Close();
            }
            return Convert.ToBase64String(array);
        }

        public static string Decrypt(string encryptedText)
        {
            byte[] buffer = Convert.FromBase64String(encryptedText);
            byte[] bytes = new Rfc2898DeriveBytes(PasswordHash, Encoding.ASCII.GetBytes(SaltKey)).GetBytes(32);
            RijndaelManaged rijndaelManaged = new RijndaelManaged();
            rijndaelManaged.Mode = CipherMode.CBC;
            rijndaelManaged.Padding = PaddingMode.None;
            ICryptoTransform decryptor = rijndaelManaged.CreateDecryptor(bytes, Encoding.ASCII.GetBytes(VIKey));
            MemoryStream memoryStream = new MemoryStream(buffer);
            CryptoStream cryptoStream = new CryptoStream((Stream)memoryStream, decryptor, CryptoStreamMode.Read);
            byte[] numArray = new byte[buffer.Length];
            int count = cryptoStream.Read(numArray, 0, numArray.Length);
            memoryStream.Close();
            cryptoStream.Close();
            return Encoding.UTF8.GetString(numArray, 0, count).TrimEnd("\0".ToCharArray());
        }

}

**Comment by rnapier** [comment]
In order to decrypt RNCryptor on PHP, the C# code also needs to encrypt using [RNCryptor](https://github.com/RNCryptor/RNCryptor-cs). RNCryptor is a format, and both sides need to use the same one. Your C# code describes a custom, ad hoc encryption format. If you need to use that, then you'll need to re-implement that in PHP. RNCryptor can't help you with ad hoc formats. The major reason RNCryptor exists is so you don't need to create your own ad hoc format.

**Comment by baaslaawe** [comment]
but this who share company  they use this  C#  so  ineed to make a php

**Comment by rnapier** [comment]
Understood. You’ll need to implement something that matches their format in that case. This isn’t related to RNCryptor. RNCryptor is a specific format.
