### ISSUE TITLE
Encrypt with PHP and decrypt on iPhone problem

### ISSUE THREAD

**Issue by HTAD** [RNCryptor/RNCryptor-php#3]
I encrypt a string with secrect key on server (PHP)

public static function Encrypt($string, $password)
	{
		require __LIBS__ . '/RNCryptor/autoload.php';
		
		$cryptor = new \RNCryptor\Encryptor();
		return $cryptor->encrypt($string, $password);
	}

and try to decrypt it on iPhone

NSData* encryptedData = [@"AwH3lRq1dHsdyjsWzYmBpIVQSHkdjvGbOXLbCW1r240ZFIgFXgCj" dataUsingEncoding:NSUTF8StringEncoding];
NSData *decryptedData = [RNDecryptor decryptData:encryptedData
                                        withPassword:@"123456"
                                               error:&error];
//convert decryptedData to decryptedString but it is an empty string

Help me fix that please !

Thanks !

**Comment by elprl** [comment]
I'm having similar difficulties matching encrypted strings on PHP and iOS.

$password = "myPassword";
$plaintext = "MyData";

$cryptor = new \RNCryptor\Encryptor();
$base64Encrypted = $cryptor->encrypt($plaintext, $password);

echo "Plaintext:\n$plaintext\n\n";
echo "Base64 Encrypted:\n$base64Encrypted\n\n";

Produces output of 
"AwHwRIrxE2FOad+of7ppTAEt0IpT2t9hBgEwdWWWbHUne9nU/xT00njrOCOBIT8CcgziMxAQXBkHYh3uMCtazrPuMXdVWCC1yWFfC7hPAm8bmg=="

I need to match that string with iOS code:
    NSData *data = [[NSData alloc] initWithBase64EncodedString:@"MyData" options:0];
    NSError *error;
    NSData *encryptedData = [RNEncryptor encryptData:data
                                        withSettings:kRNCryptorAES256Settings
                                            password:@"myPassword"
                                               error:&error];
    NSString *cipherString = [encryptedData base64EncodedStringWithOptions:0];


cipherString:
"AwEtoyB3j0jnHyR8nPYtZ9s08hQ40nXb/VinwuIrOQrABqxUQWIRg2hRL8Ond9NZVBEuAFUzP+O9MbvZAkXXHhkHqDxLj8CDabSUmf6b9iqveQ=="

Shouldn't these be producing the same output?

**Comment by rnapier** [comment]
Two runs of encryptData:withSettings:password:error: should never return
the same output. There are random salts included the format to prevent that.

**Comment by elprl** [comment]
Ah, I see. Thanks for the response rnapier.

**Comment by enricodeleo** [comment]
I have a similar problem here. I'm using https://github.com/VJAI/simple-crypto in a Cordova app where I'm trying to decrypt a file that I encrypted with file_get_contents -> encrypt with this library -> file_put_contents but I get null.
Instead, if I decrypt the same file with RNCryptor-php I get the image back as expected. 
Any ideas?

**Comment by rnapier** [comment]
It looks like that library only returns and accepts base-64 encoded
strings. Are you converting your data to and from base-64?

(This is definitely not how I recommend processing data; converting to and
from base-64 is very inefficient in both time and memory, and this approach
requires you to convert three or four times for each operation. But I guess
once you've gone to JavaScript on an iPhone you've pretty much given up on
efficiency, so it may not matter that much. Hopefully your file is small.)

-Rob

On Mon, Aug 24, 2015 at 12:12 PM, Enrico Deleo <notifications@github.com>
wrote:

> I have a similar problem here. I'm using
> https://github.com/VJAI/simple-crypto in a Cordova app where I'm trying
> to decrypt a file that I encrypted with file_get_contents -> encrypt with
> this library -> file_put_contents but I get null.
> Instead, if I decrypt the same file with RNCryptor-php I get the image
> back as expected.
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RNCryptor/RNCryptor-php/issues/3#issuecomment-134272435>
> .
>



-- 
Rob Napier
Cocoaphony blog -- http://robnapier.net/blog
iOS Programming Pushing the Limits -- http://robnapier.net/book

**Comment by enricodeleo** [comment]
@rnapier I don't convert to base64 before encryption. I read the content of the file as is via file_get_contents. If I use RNCryptor-php to decrypt the same file I have no problems.

On iOS I'm not going with javascript itself but call the native objective-c RNCryptor instead, so it is pretty much native...

So do you advise to encode in base64 the file before encryption?

**Comment by rnapier** [comment]
I mean that the SimpleCrypto library you referenced, seems to require that
its data be passed in Base64. Look at the code:

https://github.com/VJAI/simple-crypto/blob/master/src/ios/SimpleCrypto.m

I don't know anything about that wrapper.

If you're using Objective-C RNCryptor, you shouldn't have a problem
interoperating with RNCryptor-php.

-Rob


On Tue, Aug 25, 2015 at 5:37 PM, Enrico Deleo <notifications@github.com>
wrote:

> @rnapier <https://github.com/rnapier> I don't convert to base64 before
> encryption. I read the content of the file as is via file_get_contents. If
> I use RNCryptor-php to decrypt the same file I have no problems.
>
> On iOS I'm not going with javascript itself but call the native
> objective-c RNCryptor instead, so it is pretty much native...
>
> So do you advise to encode in base64 the file before encryption?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RNCryptor/RNCryptor-php/issues/3#issuecomment-134749404>
> .
>



-- 
Rob Napier
Cocoaphony blog -- http://robnapier.net/blog
iOS Programming Pushing the Limits -- http://robnapier.net/book

**Comment by enricodeleo** [comment]
@rnapier in fact passing the original file as base64 it does the trick. Probably because decrypting a file should be treated as blob. May be I need to write a new cordova plugin that better fit this need. 
Thank you for your help!

**Comment by enricodeleo** [comment]
@rnapier after a few test I discovered that if I `base64_decode` the string (actually its binary data since I encrypt jpegs) encrypted by RNCryptor-php before saving the file, the plugin works.

In fact RNCryptor-php encodes the encrypted data before returning it. The solution is either avoid the first base64 encoding (that is what I'm going to do) or decode the base 64 string on the other end before decrypt.

**Comment by curtisdf** [comment]
I believe this issue is solved. Although I haven't addressed the preference for not base64 encoding on input/output.  If someone feels this is really a performance problem, please kindly report it in another thread. Thanks!
