### ISSUE TITLE
Call to undefined function RNCryptor\hash_pbkdf2()

### ISSUE THREAD

**Issue by nullproduction** [RNCryptor/RNCryptor-php#4]
Call to undefined function RNCryptor\hash_pbkdf2()

php 5.4.19

**Comment by nullproduction** [comment]
I found solution, it backport pbkdf2 function  - https://gist.github.com/rsky/5104756

**Comment by paragonie-scott** [comment]
The solution here is to use absolute function resolution when operating withing a namespace. i.e.

```diff
- hash_pbkdf2()
+ \hash_pbkdf2()
```

**Comment by curtisdf** [comment]
We are now using a polyfill library to handle hash_pbkdf2().  I believe this solves the problem.
