### ISSUE TITLE
Issues Decrypting Image File from Android to PHP

### ISSUE THREAD

**Issue by shevyshapiro** [RNCryptor/RNCryptor-php#8]
I encrypt an image file on Android, and then upload it to the server. In PHP, I try to decrypt, but it keeps getting errors. Sometimes base64_decode returns nothing, sometimes I get 
Fatal error: Uncaught exception 'Exception' with message 'Unsupported schema version 23' in Cryptor.php. 

Android:

                File file = new File(Environment.getExternalStorageDirectory()
                        .getPath() + "/" + filename);

                byte[] originalBytes = FileUtils.readFileToByteArray(file);
                byte[] encryptedBytes = new AES256JNCryptor().encryptData(originalBytes, "test".toCharArray());

                FileUtils.writeByteArrayToFile(file, encryptedBytes);

PHP:
               $string = file_get_contents($file);
               $decryptor = new \RNCryptor\Decryptor();
               $decryptedData` = $decryptor->decrypt($string, "test");

**Comment by JavaMachine** [comment]
$fileBinary = fread(fopen($file, "r"), filesize($file));
$decryptor = new \RNCryptor\Decryptor();
$decryptedData` = $decryptor->decrypt($fileBinary, "test");

I had problems with using "file_get_contents()", even if documentation states this function is "Binary-Safe"

**Comment by curtisdf** [comment]
I'm not sure what to say @JavaMachine .  The "Unsupported schema version" error refers to the fact that there are multiple versions of the RNCryptor byte stream.  The decryption function looks at the first chunk of an incoming byte stream, and if it doesn't match a known version number, then it will fail with that error.

If base64_decode() is behaving inconsistently, then it could be a problem we've heard about fairly often, and which I myself was confounded by for a time, where URL Encoding ends up being the culprit.  The Base64 algorithm occasionally outputs characters that would require being escaped if the encrypted data was put into an HTTP POST or GET request.  So if you are transferring your data that way, you will need to ensure that a URL Decode function is run on the receiving end to undo that escaping.

But if you are transferring your data through some other mechanism that doesn't do any escaping like this, then we'd need to look for other ideas.

**Comment by rnapier** [comment]
This is almost certainly an encoding issue. If it is ongoing and you believe you have precisely the same bytes going into the decryptor that came out of the encryptor, please reopen with an example and we'll be happy to dig into it.
