### ISSUE TITLE
Using Key to Encrypt and Decrypt data

### ISSUE THREAD

**Issue by JavaMachine** [RNCryptor/RNCryptor-php#9]
Hello fellow developers,

I was looking for ways of optimizing and reducing encryption/decryption time...

From the examples I can see that I need to encrypt / decrypt data using 'plain text password' and Library generates key from that 'plain text password'...

Is there any possibilities that I could use that generated KEY straight away without loosing time on its generation?

Thanks in advance.

**Comment by rnapier** [comment]
Do you need password support at all, or can you work entirely with randomly generated keys? Can you give just a sketch of the problem you're solving? Broadly, the answer is yes, but it depends a little on exactly what problem you're trying to solve.

If you can work entirely on random keys, and don't need a human readable password at all, it's pretty easy. You just need to generate two random AES keys, and then for each encryption generate a random IV and call.

	public function encryptWithArbitraryKeys($plaintext, $encKey, $hmacKey, $iv, $version = Cryptor::DEFAULT_SCHEMA_VERSION) {

See `_generateIv` for an example of how to generate random data.

**Comment by JavaMachine** [comment]
Yes, I am working with randomly generated 'passwords' (they are not human readable at all)

IMHO: Generating a PBKDF2 key is expensive operation and we are trying to use already generated PBKDF2 key on every encryption/decryption (with this we can avoid expensive PBKDF2 key generation)

`public function encryptWithArbitraryKeys($plaintext, $encKey, $hmacKey, $iv, $version = Cryptor::DEFAULT_SCHEMA_VERSION)`

Could solve the problem but, as far as I know If I encrypt with KEY (not password) then the other side should decrypt it with KEY (not password) and vise versa...

And here is the another problem, `Decryptor `class does not have `decryptWithArbitraryKeys` method...

Well I can surely edit my local copy of library for my own needs, and implement simpler solution...

**Comment by JavaMachine** [comment]
I am thinking about implementing my own `public function encrypt($plaintext, Key $key, $version = Cryptor::DEFAULT_SCHEMA_VERSION)` and `public function decrypt($plaintext, Key $key)` methods...

**Comment by curtisdf** [comment]
Hi @JavaMachine. Sounds like if we just had `decryptWithArbitraryKeys`, this would solve your dilemma.  Is that correct? If so, we'd be happy to see a pull request.

The `encryptWithArbitraryKeys` method was implemented mainly to facilitate testing. But a decrypt version would certainly help balance things out.
